services:
  pgdatabase:
    image : postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  pgadmin:
    image : dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
     - "8080:80"


volumes:
  vol-pgdata:
    external: true
